/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminItemResponse
 */
export interface AdminItemResponse {
    /**
     * 
     * @type {number}
     * @memberof AdminItemResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AdminItemResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminItemResponse
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminItemResponse
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminItemResponse
     */
    brand?: string;
    /**
     * 
     * @type {number}
     * @memberof AdminItemResponse
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminItemResponse
     */
    initialStockQuantity?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminItemResponse
     */
    soldStockQuantity?: number;
}

/**
 * Check if a given object implements the AdminItemResponse interface.
 */
export function instanceOfAdminItemResponse(value: object): value is AdminItemResponse {
    return true;
}

export function AdminItemResponseFromJSON(json: any): AdminItemResponse {
    return AdminItemResponseFromJSONTyped(json, false);
}

export function AdminItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'type': json['type'] == null ? undefined : json['type'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'price': json['price'] == null ? undefined : json['price'],
        'initialStockQuantity': json['initialStockQuantity'] == null ? undefined : json['initialStockQuantity'],
        'soldStockQuantity': json['soldStockQuantity'] == null ? undefined : json['soldStockQuantity'],
    };
}

export function AdminItemResponseToJSON(json: any): AdminItemResponse {
    return AdminItemResponseToJSONTyped(json, false);
}

export function AdminItemResponseToJSONTyped(value?: AdminItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'imageUrl': value['imageUrl'],
        'type': value['type'],
        'brand': value['brand'],
        'price': value['price'],
        'initialStockQuantity': value['initialStockQuantity'],
        'soldStockQuantity': value['soldStockQuantity'],
    };
}

