/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeDealModalCreateResponse } from './TimeDealModalCreateResponse';
import {
    TimeDealModalCreateResponseFromJSON,
    TimeDealModalCreateResponseFromJSONTyped,
    TimeDealModalCreateResponseToJSON,
    TimeDealModalCreateResponseToJSONTyped,
} from './TimeDealModalCreateResponse';

/**
 * 
 * @export
 * @interface BaseResponseListTimeDealModalCreateResponse
 */
export interface BaseResponseListTimeDealModalCreateResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseListTimeDealModalCreateResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListTimeDealModalCreateResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListTimeDealModalCreateResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseListTimeDealModalCreateResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<TimeDealModalCreateResponse>}
     * @memberof BaseResponseListTimeDealModalCreateResponse
     */
    result?: Array<TimeDealModalCreateResponse>;
}

/**
 * Check if a given object implements the BaseResponseListTimeDealModalCreateResponse interface.
 */
export function instanceOfBaseResponseListTimeDealModalCreateResponse(value: object): value is BaseResponseListTimeDealModalCreateResponse {
    return true;
}

export function BaseResponseListTimeDealModalCreateResponseFromJSON(json: any): BaseResponseListTimeDealModalCreateResponse {
    return BaseResponseListTimeDealModalCreateResponseFromJSONTyped(json, false);
}

export function BaseResponseListTimeDealModalCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseListTimeDealModalCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(TimeDealModalCreateResponseFromJSON)),
    };
}

export function BaseResponseListTimeDealModalCreateResponseToJSON(json: any): BaseResponseListTimeDealModalCreateResponse {
    return BaseResponseListTimeDealModalCreateResponseToJSONTyped(json, false);
}

export function BaseResponseListTimeDealModalCreateResponseToJSONTyped(value?: BaseResponseListTimeDealModalCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(TimeDealModalCreateResponseToJSON)),
    };
}

