/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseTimeDealSearchResponse } from './PageResponseTimeDealSearchResponse';
import {
    PageResponseTimeDealSearchResponseFromJSON,
    PageResponseTimeDealSearchResponseFromJSONTyped,
    PageResponseTimeDealSearchResponseToJSON,
    PageResponseTimeDealSearchResponseToJSONTyped,
} from './PageResponseTimeDealSearchResponse';

/**
 * 
 * @export
 * @interface BaseResponsePageResponseTimeDealSearchResponse
 */
export interface BaseResponsePageResponseTimeDealSearchResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponsePageResponseTimeDealSearchResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePageResponseTimeDealSearchResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePageResponseTimeDealSearchResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponsePageResponseTimeDealSearchResponse
     */
    message?: string;
    /**
     * 
     * @type {PageResponseTimeDealSearchResponse}
     * @memberof BaseResponsePageResponseTimeDealSearchResponse
     */
    result?: PageResponseTimeDealSearchResponse;
}

/**
 * Check if a given object implements the BaseResponsePageResponseTimeDealSearchResponse interface.
 */
export function instanceOfBaseResponsePageResponseTimeDealSearchResponse(value: object): value is BaseResponsePageResponseTimeDealSearchResponse {
    return true;
}

export function BaseResponsePageResponseTimeDealSearchResponseFromJSON(json: any): BaseResponsePageResponseTimeDealSearchResponse {
    return BaseResponsePageResponseTimeDealSearchResponseFromJSONTyped(json, false);
}

export function BaseResponsePageResponseTimeDealSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponsePageResponseTimeDealSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : PageResponseTimeDealSearchResponseFromJSON(json['result']),
    };
}

export function BaseResponsePageResponseTimeDealSearchResponseToJSON(json: any): BaseResponsePageResponseTimeDealSearchResponse {
    return BaseResponsePageResponseTimeDealSearchResponseToJSONTyped(json, false);
}

export function BaseResponsePageResponseTimeDealSearchResponseToJSONTyped(value?: BaseResponsePageResponseTimeDealSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': PageResponseTimeDealSearchResponseToJSON(value['result']),
    };
}

