/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseAdminItemResponse } from './PageResponseAdminItemResponse';
import {
    PageResponseAdminItemResponseFromJSON,
    PageResponseAdminItemResponseFromJSONTyped,
    PageResponseAdminItemResponseToJSON,
    PageResponseAdminItemResponseToJSONTyped,
} from './PageResponseAdminItemResponse';

/**
 * 
 * @export
 * @interface BaseResponsePageResponseAdminItemResponse
 */
export interface BaseResponsePageResponseAdminItemResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponsePageResponseAdminItemResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePageResponseAdminItemResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePageResponseAdminItemResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponsePageResponseAdminItemResponse
     */
    message?: string;
    /**
     * 
     * @type {PageResponseAdminItemResponse}
     * @memberof BaseResponsePageResponseAdminItemResponse
     */
    result?: PageResponseAdminItemResponse;
}

/**
 * Check if a given object implements the BaseResponsePageResponseAdminItemResponse interface.
 */
export function instanceOfBaseResponsePageResponseAdminItemResponse(value: object): value is BaseResponsePageResponseAdminItemResponse {
    return true;
}

export function BaseResponsePageResponseAdminItemResponseFromJSON(json: any): BaseResponsePageResponseAdminItemResponse {
    return BaseResponsePageResponseAdminItemResponseFromJSONTyped(json, false);
}

export function BaseResponsePageResponseAdminItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponsePageResponseAdminItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : PageResponseAdminItemResponseFromJSON(json['result']),
    };
}

export function BaseResponsePageResponseAdminItemResponseToJSON(json: any): BaseResponsePageResponseAdminItemResponse {
    return BaseResponsePageResponseAdminItemResponseToJSONTyped(json, false);
}

export function BaseResponsePageResponseAdminItemResponseToJSONTyped(value?: BaseResponsePageResponseAdminItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': PageResponseAdminItemResponseToJSON(value['result']),
    };
}

