/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CartResponse } from './CartResponse';
import {
    CartResponseFromJSON,
    CartResponseFromJSONTyped,
    CartResponseToJSON,
    CartResponseToJSONTyped,
} from './CartResponse';

/**
 * 
 * @export
 * @interface BaseResponseCartResponse
 */
export interface BaseResponseCartResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseCartResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseCartResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseCartResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCartResponse
     */
    message?: string;
    /**
     * 
     * @type {CartResponse}
     * @memberof BaseResponseCartResponse
     */
    result?: CartResponse;
}

/**
 * Check if a given object implements the BaseResponseCartResponse interface.
 */
export function instanceOfBaseResponseCartResponse(value: object): value is BaseResponseCartResponse {
    return true;
}

export function BaseResponseCartResponseFromJSON(json: any): BaseResponseCartResponse {
    return BaseResponseCartResponseFromJSONTyped(json, false);
}

export function BaseResponseCartResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCartResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : CartResponseFromJSON(json['result']),
    };
}

export function BaseResponseCartResponseToJSON(json: any): BaseResponseCartResponse {
    return BaseResponseCartResponseToJSONTyped(json, false);
}

export function BaseResponseCartResponseToJSONTyped(value?: BaseResponseCartResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': CartResponseToJSON(value['result']),
    };
}

