/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseSimpleItemResponse } from './PageResponseSimpleItemResponse';
import {
    PageResponseSimpleItemResponseFromJSON,
    PageResponseSimpleItemResponseFromJSONTyped,
    PageResponseSimpleItemResponseToJSON,
    PageResponseSimpleItemResponseToJSONTyped,
} from './PageResponseSimpleItemResponse';

/**
 * 
 * @export
 * @interface BaseResponsePageResponseSimpleItemResponse
 */
export interface BaseResponsePageResponseSimpleItemResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponsePageResponseSimpleItemResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePageResponseSimpleItemResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePageResponseSimpleItemResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponsePageResponseSimpleItemResponse
     */
    message?: string;
    /**
     * 
     * @type {PageResponseSimpleItemResponse}
     * @memberof BaseResponsePageResponseSimpleItemResponse
     */
    result?: PageResponseSimpleItemResponse;
}

/**
 * Check if a given object implements the BaseResponsePageResponseSimpleItemResponse interface.
 */
export function instanceOfBaseResponsePageResponseSimpleItemResponse(value: object): value is BaseResponsePageResponseSimpleItemResponse {
    return true;
}

export function BaseResponsePageResponseSimpleItemResponseFromJSON(json: any): BaseResponsePageResponseSimpleItemResponse {
    return BaseResponsePageResponseSimpleItemResponseFromJSONTyped(json, false);
}

export function BaseResponsePageResponseSimpleItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponsePageResponseSimpleItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : PageResponseSimpleItemResponseFromJSON(json['result']),
    };
}

export function BaseResponsePageResponseSimpleItemResponseToJSON(json: any): BaseResponsePageResponseSimpleItemResponse {
    return BaseResponsePageResponseSimpleItemResponseToJSONTyped(json, false);
}

export function BaseResponsePageResponseSimpleItemResponseToJSONTyped(value?: BaseResponsePageResponseSimpleItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': PageResponseSimpleItemResponseToJSON(value['result']),
    };
}

