/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MyPageInfoDTO } from './MyPageInfoDTO';
import {
    MyPageInfoDTOFromJSON,
    MyPageInfoDTOFromJSONTyped,
    MyPageInfoDTOToJSON,
    MyPageInfoDTOToJSONTyped,
} from './MyPageInfoDTO';

/**
 * 
 * @export
 * @interface BaseResponseMyPageInfoDTO
 */
export interface BaseResponseMyPageInfoDTO {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseMyPageInfoDTO
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseMyPageInfoDTO
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseMyPageInfoDTO
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseMyPageInfoDTO
     */
    message?: string;
    /**
     * 
     * @type {MyPageInfoDTO}
     * @memberof BaseResponseMyPageInfoDTO
     */
    result?: MyPageInfoDTO;
}

/**
 * Check if a given object implements the BaseResponseMyPageInfoDTO interface.
 */
export function instanceOfBaseResponseMyPageInfoDTO(value: object): value is BaseResponseMyPageInfoDTO {
    return true;
}

export function BaseResponseMyPageInfoDTOFromJSON(json: any): BaseResponseMyPageInfoDTO {
    return BaseResponseMyPageInfoDTOFromJSONTyped(json, false);
}

export function BaseResponseMyPageInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseMyPageInfoDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : MyPageInfoDTOFromJSON(json['result']),
    };
}

export function BaseResponseMyPageInfoDTOToJSON(json: any): BaseResponseMyPageInfoDTO {
    return BaseResponseMyPageInfoDTOToJSONTyped(json, false);
}

export function BaseResponseMyPageInfoDTOToJSONTyped(value?: BaseResponseMyPageInfoDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': MyPageInfoDTOToJSON(value['result']),
    };
}

