/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrentTimeDealResponse } from './CurrentTimeDealResponse';
import {
    CurrentTimeDealResponseFromJSON,
    CurrentTimeDealResponseFromJSONTyped,
    CurrentTimeDealResponseToJSON,
    CurrentTimeDealResponseToJSONTyped,
} from './CurrentTimeDealResponse';

/**
 * 
 * @export
 * @interface BaseResponseCurrentTimeDealResponse
 */
export interface BaseResponseCurrentTimeDealResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseCurrentTimeDealResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseCurrentTimeDealResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseCurrentTimeDealResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCurrentTimeDealResponse
     */
    message?: string;
    /**
     * 
     * @type {CurrentTimeDealResponse}
     * @memberof BaseResponseCurrentTimeDealResponse
     */
    result?: CurrentTimeDealResponse;
}

/**
 * Check if a given object implements the BaseResponseCurrentTimeDealResponse interface.
 */
export function instanceOfBaseResponseCurrentTimeDealResponse(value: object): value is BaseResponseCurrentTimeDealResponse {
    return true;
}

export function BaseResponseCurrentTimeDealResponseFromJSON(json: any): BaseResponseCurrentTimeDealResponse {
    return BaseResponseCurrentTimeDealResponseFromJSONTyped(json, false);
}

export function BaseResponseCurrentTimeDealResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCurrentTimeDealResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : CurrentTimeDealResponseFromJSON(json['result']),
    };
}

export function BaseResponseCurrentTimeDealResponseToJSON(json: any): BaseResponseCurrentTimeDealResponse {
    return BaseResponseCurrentTimeDealResponseToJSONTyped(json, false);
}

export function BaseResponseCurrentTimeDealResponseToJSONTyped(value?: BaseResponseCurrentTimeDealResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': CurrentTimeDealResponseToJSON(value['result']),
    };
}

