/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeDealCreateResponse } from './TimeDealCreateResponse';
import {
    TimeDealCreateResponseFromJSON,
    TimeDealCreateResponseFromJSONTyped,
    TimeDealCreateResponseToJSON,
    TimeDealCreateResponseToJSONTyped,
} from './TimeDealCreateResponse';

/**
 * 
 * @export
 * @interface BaseResponseTimeDealCreateResponse
 */
export interface BaseResponseTimeDealCreateResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseTimeDealCreateResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseTimeDealCreateResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseTimeDealCreateResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseTimeDealCreateResponse
     */
    message?: string;
    /**
     * 
     * @type {TimeDealCreateResponse}
     * @memberof BaseResponseTimeDealCreateResponse
     */
    result?: TimeDealCreateResponse;
}

/**
 * Check if a given object implements the BaseResponseTimeDealCreateResponse interface.
 */
export function instanceOfBaseResponseTimeDealCreateResponse(value: object): value is BaseResponseTimeDealCreateResponse {
    return true;
}

export function BaseResponseTimeDealCreateResponseFromJSON(json: any): BaseResponseTimeDealCreateResponse {
    return BaseResponseTimeDealCreateResponseFromJSONTyped(json, false);
}

export function BaseResponseTimeDealCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseTimeDealCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : TimeDealCreateResponseFromJSON(json['result']),
    };
}

export function BaseResponseTimeDealCreateResponseToJSON(json: any): BaseResponseTimeDealCreateResponse {
    return BaseResponseTimeDealCreateResponseToJSONTyped(json, false);
}

export function BaseResponseTimeDealCreateResponseToJSONTyped(value?: BaseResponseTimeDealCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': TimeDealCreateResponseToJSON(value['result']),
    };
}

