/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Brand
 */
export interface Brand {
    /**
     * 
     * @type {number}
     * @memberof Brand
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof Brand
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Brand
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Brand
     */
    name?: string;
}

/**
 * Check if a given object implements the Brand interface.
 */
export function instanceOfBrand(value: object): value is Brand {
    return true;
}

export function BrandFromJSON(json: any): Brand {
    return BrandFromJSONTyped(json, false);
}

export function BrandFromJSONTyped(json: any, ignoreDiscriminator: boolean): Brand {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function BrandToJSON(json: any): Brand {
    return BrandToJSONTyped(json, false);
}

export function BrandToJSONTyped(value?: Brand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'name': value['name'],
    };
}

