/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 장바구니 상품 응답 DTO
 * @export
 * @interface CartItemResponse
 */
export interface CartItemResponse {
    /**
     * 장바구니 아이템 ID
     * @type {number}
     * @memberof CartItemResponse
     */
    cartItemId?: number;
    /**
     * 상품 ID
     * @type {number}
     * @memberof CartItemResponse
     */
    itemId?: number;
    /**
     * 상품명
     * @type {string}
     * @memberof CartItemResponse
     */
    itemName?: string;
    /**
     * 상품 종류
     * @type {string}
     * @memberof CartItemResponse
     */
    type?: string;
    /**
     * 브랜드명
     * @type {string}
     * @memberof CartItemResponse
     */
    brand?: string;
    /**
     * 수량
     * @type {number}
     * @memberof CartItemResponse
     */
    quantity?: number;
    /**
     * 상품 이미지 URL
     * @type {string}
     * @memberof CartItemResponse
     */
    imageUrl?: string;
    /**
     * 상품 정가
     * @type {number}
     * @memberof CartItemResponse
     */
    originalPrice?: number;
    /**
     * 할인 적용된 가격
     * @type {number}
     * @memberof CartItemResponse
     */
    discountedPrice?: number;
    /**
     * 총 가격 (수량 * 할인 가격)
     * @type {number}
     * @memberof CartItemResponse
     */
    totalPrice?: number;
    /**
     * 할인율
     * @type {number}
     * @memberof CartItemResponse
     */
    discountRatio?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CartItemResponse
     */
    timeDeal?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CartItemResponse
     */
    soldOut?: boolean;
}

/**
 * Check if a given object implements the CartItemResponse interface.
 */
export function instanceOfCartItemResponse(value: object): value is CartItemResponse {
    return true;
}

export function CartItemResponseFromJSON(json: any): CartItemResponse {
    return CartItemResponseFromJSONTyped(json, false);
}

export function CartItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cartItemId': json['cartItemId'] == null ? undefined : json['cartItemId'],
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'itemName': json['itemName'] == null ? undefined : json['itemName'],
        'type': json['type'] == null ? undefined : json['type'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'originalPrice': json['originalPrice'] == null ? undefined : json['originalPrice'],
        'discountedPrice': json['discountedPrice'] == null ? undefined : json['discountedPrice'],
        'totalPrice': json['totalPrice'] == null ? undefined : json['totalPrice'],
        'discountRatio': json['discountRatio'] == null ? undefined : json['discountRatio'],
        'timeDeal': json['timeDeal'] == null ? undefined : json['timeDeal'],
        'soldOut': json['soldOut'] == null ? undefined : json['soldOut'],
    };
}

export function CartItemResponseToJSON(json: any): CartItemResponse {
    return CartItemResponseToJSONTyped(json, false);
}

export function CartItemResponseToJSONTyped(value?: CartItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cartItemId': value['cartItemId'],
        'itemId': value['itemId'],
        'itemName': value['itemName'],
        'type': value['type'],
        'brand': value['brand'],
        'quantity': value['quantity'],
        'imageUrl': value['imageUrl'],
        'originalPrice': value['originalPrice'],
        'discountedPrice': value['discountedPrice'],
        'totalPrice': value['totalPrice'],
        'discountRatio': value['discountRatio'],
        'timeDeal': value['timeDeal'],
        'soldOut': value['soldOut'],
    };
}

