/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CartItemAddRequest
 */
export interface CartItemAddRequest {
    /**
     * 
     * @type {number}
     * @memberof CartItemAddRequest
     */
    itemId: number;
    /**
     * 
     * @type {number}
     * @memberof CartItemAddRequest
     */
    quantity: number;
}

/**
 * Check if a given object implements the CartItemAddRequest interface.
 */
export function instanceOfCartItemAddRequest(value: object): value is CartItemAddRequest {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function CartItemAddRequestFromJSON(json: any): CartItemAddRequest {
    return CartItemAddRequestFromJSONTyped(json, false);
}

export function CartItemAddRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemAddRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'],
        'quantity': json['quantity'],
    };
}

export function CartItemAddRequestToJSON(json: any): CartItemAddRequest {
    return CartItemAddRequestToJSONTyped(json, false);
}

export function CartItemAddRequestToJSONTyped(value?: CartItemAddRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'quantity': value['quantity'],
    };
}

