/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Brand } from './Brand';
import {
    BrandFromJSON,
    BrandFromJSONTyped,
    BrandToJSON,
    BrandToJSONTyped,
} from './Brand';
import type { Type } from './Type';
import {
    TypeFromJSON,
    TypeFromJSONTyped,
    TypeToJSON,
    TypeToJSONTyped,
} from './Type';

/**
 * 
 * @export
 * @interface CurrentTimeDealItem
 */
export interface CurrentTimeDealItem {
    /**
     * 
     * @type {number}
     * @memberof CurrentTimeDealItem
     */
    itemId?: number;
    /**
     * 
     * @type {string}
     * @memberof CurrentTimeDealItem
     */
    imageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof CurrentTimeDealItem
     */
    originalPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrentTimeDealItem
     */
    discountedPrice?: number;
    /**
     * 
     * @type {Type}
     * @memberof CurrentTimeDealItem
     */
    type?: Type;
    /**
     * 
     * @type {Brand}
     * @memberof CurrentTimeDealItem
     */
    brand?: Brand;
}

/**
 * Check if a given object implements the CurrentTimeDealItem interface.
 */
export function instanceOfCurrentTimeDealItem(value: object): value is CurrentTimeDealItem {
    return true;
}

export function CurrentTimeDealItemFromJSON(json: any): CurrentTimeDealItem {
    return CurrentTimeDealItemFromJSONTyped(json, false);
}

export function CurrentTimeDealItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentTimeDealItem {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'originalPrice': json['originalPrice'] == null ? undefined : json['originalPrice'],
        'discountedPrice': json['discountedPrice'] == null ? undefined : json['discountedPrice'],
        'type': json['type'] == null ? undefined : TypeFromJSON(json['type']),
        'brand': json['brand'] == null ? undefined : BrandFromJSON(json['brand']),
    };
}

export function CurrentTimeDealItemToJSON(json: any): CurrentTimeDealItem {
    return CurrentTimeDealItemToJSONTyped(json, false);
}

export function CurrentTimeDealItemToJSONTyped(value?: CurrentTimeDealItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'imageUrl': value['imageUrl'],
        'originalPrice': value['originalPrice'],
        'discountedPrice': value['discountedPrice'],
        'type': TypeToJSON(value['type']),
        'brand': BrandToJSON(value['brand']),
    };
}

