/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemUpdateRequest
 */
export interface ItemUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof ItemUpdateRequest
     */
    stockQuantity?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemUpdateRequest
     */
    price?: number;
}

/**
 * Check if a given object implements the ItemUpdateRequest interface.
 */
export function instanceOfItemUpdateRequest(value: object): value is ItemUpdateRequest {
    return true;
}

export function ItemUpdateRequestFromJSON(json: any): ItemUpdateRequest {
    return ItemUpdateRequestFromJSONTyped(json, false);
}

export function ItemUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'stockQuantity': json['stockQuantity'] == null ? undefined : json['stockQuantity'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function ItemUpdateRequestToJSON(json: any): ItemUpdateRequest {
    return ItemUpdateRequestToJSONTyped(json, false);
}

export function ItemUpdateRequestToJSONTyped(value?: ItemUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stockQuantity': value['stockQuantity'],
        'price': value['price'],
    };
}

