/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MyPageInfoDTO
 */
export interface MyPageInfoDTO {
    /**
     * 
     * @type {string}
     * @memberof MyPageInfoDTO
     */
    memberName?: string;
    /**
     * 
     * @type {string}
     * @memberof MyPageInfoDTO
     */
    memberAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof MyPageInfoDTO
     */
    memberAddressDetail?: string;
}

/**
 * Check if a given object implements the MyPageInfoDTO interface.
 */
export function instanceOfMyPageInfoDTO(value: object): value is MyPageInfoDTO {
    return true;
}

export function MyPageInfoDTOFromJSON(json: any): MyPageInfoDTO {
    return MyPageInfoDTOFromJSONTyped(json, false);
}

export function MyPageInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyPageInfoDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'memberName': json['memberName'] == null ? undefined : json['memberName'],
        'memberAddress': json['memberAddress'] == null ? undefined : json['memberAddress'],
        'memberAddressDetail': json['memberAddressDetail'] == null ? undefined : json['memberAddressDetail'],
    };
}

export function MyPageInfoDTOToJSON(json: any): MyPageInfoDTO {
    return MyPageInfoDTOToJSONTyped(json, false);
}

export function MyPageInfoDTOToJSONTyped(value?: MyPageInfoDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'memberName': value['memberName'],
        'memberAddress': value['memberAddress'],
        'memberAddressDetail': value['memberAddressDetail'],
    };
}

