/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MyPageAddressUpdateDTO
 */
export interface MyPageAddressUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof MyPageAddressUpdateDTO
     */
    memberAddress: string;
    /**
     * 
     * @type {string}
     * @memberof MyPageAddressUpdateDTO
     */
    memberAddressDetail?: string;
}

/**
 * Check if a given object implements the MyPageAddressUpdateDTO interface.
 */
export function instanceOfMyPageAddressUpdateDTO(value: object): value is MyPageAddressUpdateDTO {
    if (!('memberAddress' in value) || value['memberAddress'] === undefined) return false;
    return true;
}

export function MyPageAddressUpdateDTOFromJSON(json: any): MyPageAddressUpdateDTO {
    return MyPageAddressUpdateDTOFromJSONTyped(json, false);
}

export function MyPageAddressUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyPageAddressUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'memberAddress': json['memberAddress'],
        'memberAddressDetail': json['memberAddressDetail'] == null ? undefined : json['memberAddressDetail'],
    };
}

export function MyPageAddressUpdateDTOToJSON(json: any): MyPageAddressUpdateDTO {
    return MyPageAddressUpdateDTOToJSONTyped(json, false);
}

export function MyPageAddressUpdateDTOToJSONTyped(value?: MyPageAddressUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'memberAddress': value['memberAddress'],
        'memberAddressDetail': value['memberAddressDetail'],
    };
}

