/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderItemRequestDto
 */
export interface OrderItemRequestDto {
    /**
     * 
     * @type {number}
     * @memberof OrderItemRequestDto
     */
    itemId?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItemRequestDto
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderItemRequestDto
     */
    itemName?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderItemRequestDto
     */
    price?: number;
}

/**
 * Check if a given object implements the OrderItemRequestDto interface.
 */
export function instanceOfOrderItemRequestDto(value: object): value is OrderItemRequestDto {
    return true;
}

export function OrderItemRequestDtoFromJSON(json: any): OrderItemRequestDto {
    return OrderItemRequestDtoFromJSONTyped(json, false);
}

export function OrderItemRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderItemRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'itemName': json['itemName'] == null ? undefined : json['itemName'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function OrderItemRequestDtoToJSON(json: any): OrderItemRequestDto {
    return OrderItemRequestDtoToJSONTyped(json, false);
}

export function OrderItemRequestDtoToJSONTyped(value?: OrderItemRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'quantity': value['quantity'],
        'itemName': value['itemName'],
        'price': value['price'],
    };
}

