/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimpleItemResponse } from './SimpleItemResponse';
import {
    SimpleItemResponseFromJSON,
    SimpleItemResponseFromJSONTyped,
    SimpleItemResponseToJSON,
    SimpleItemResponseToJSONTyped,
} from './SimpleItemResponse';

/**
 * 
 * @export
 * @interface PageResponseSimpleItemResponse
 */
export interface PageResponseSimpleItemResponse {
    /**
     * 
     * @type {Array<SimpleItemResponse>}
     * @memberof PageResponseSimpleItemResponse
     */
    content?: Array<SimpleItemResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseSimpleItemResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseSimpleItemResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseSimpleItemResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseSimpleItemResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageResponseSimpleItemResponse
     */
    last?: boolean;
}

/**
 * Check if a given object implements the PageResponseSimpleItemResponse interface.
 */
export function instanceOfPageResponseSimpleItemResponse(value: object): value is PageResponseSimpleItemResponse {
    return true;
}

export function PageResponseSimpleItemResponseFromJSON(json: any): PageResponseSimpleItemResponse {
    return PageResponseSimpleItemResponseFromJSONTyped(json, false);
}

export function PageResponseSimpleItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseSimpleItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(SimpleItemResponseFromJSON)),
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'last': json['last'] == null ? undefined : json['last'],
    };
}

export function PageResponseSimpleItemResponseToJSON(json: any): PageResponseSimpleItemResponse {
    return PageResponseSimpleItemResponseToJSONTyped(json, false);
}

export function PageResponseSimpleItemResponseToJSONTyped(value?: PageResponseSimpleItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(SimpleItemResponseToJSON)),
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'last': value['last'],
    };
}

