/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminItemResponse } from './AdminItemResponse';
import {
    AdminItemResponseFromJSON,
    AdminItemResponseFromJSONTyped,
    AdminItemResponseToJSON,
    AdminItemResponseToJSONTyped,
} from './AdminItemResponse';

/**
 * 
 * @export
 * @interface PageResponseAdminItemResponse
 */
export interface PageResponseAdminItemResponse {
    /**
     * 
     * @type {Array<AdminItemResponse>}
     * @memberof PageResponseAdminItemResponse
     */
    content?: Array<AdminItemResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseAdminItemResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseAdminItemResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseAdminItemResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseAdminItemResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageResponseAdminItemResponse
     */
    last?: boolean;
}

/**
 * Check if a given object implements the PageResponseAdminItemResponse interface.
 */
export function instanceOfPageResponseAdminItemResponse(value: object): value is PageResponseAdminItemResponse {
    return true;
}

export function PageResponseAdminItemResponseFromJSON(json: any): PageResponseAdminItemResponse {
    return PageResponseAdminItemResponseFromJSONTyped(json, false);
}

export function PageResponseAdminItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseAdminItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(AdminItemResponseFromJSON)),
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'last': json['last'] == null ? undefined : json['last'],
    };
}

export function PageResponseAdminItemResponseToJSON(json: any): PageResponseAdminItemResponse {
    return PageResponseAdminItemResponseToJSONTyped(json, false);
}

export function PageResponseAdminItemResponseToJSONTyped(value?: PageResponseAdminItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(AdminItemResponseToJSON)),
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'last': value['last'],
    };
}

