/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeDealSearchResponse } from './TimeDealSearchResponse';
import {
    TimeDealSearchResponseFromJSON,
    TimeDealSearchResponseFromJSONTyped,
    TimeDealSearchResponseToJSON,
    TimeDealSearchResponseToJSONTyped,
} from './TimeDealSearchResponse';

/**
 * 
 * @export
 * @interface PageResponseTimeDealSearchResponse
 */
export interface PageResponseTimeDealSearchResponse {
    /**
     * 
     * @type {Array<TimeDealSearchResponse>}
     * @memberof PageResponseTimeDealSearchResponse
     */
    content?: Array<TimeDealSearchResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseTimeDealSearchResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseTimeDealSearchResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseTimeDealSearchResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseTimeDealSearchResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageResponseTimeDealSearchResponse
     */
    last?: boolean;
}

/**
 * Check if a given object implements the PageResponseTimeDealSearchResponse interface.
 */
export function instanceOfPageResponseTimeDealSearchResponse(value: object): value is PageResponseTimeDealSearchResponse {
    return true;
}

export function PageResponseTimeDealSearchResponseFromJSON(json: any): PageResponseTimeDealSearchResponse {
    return PageResponseTimeDealSearchResponseFromJSONTyped(json, false);
}

export function PageResponseTimeDealSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseTimeDealSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(TimeDealSearchResponseFromJSON)),
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'last': json['last'] == null ? undefined : json['last'],
    };
}

export function PageResponseTimeDealSearchResponseToJSON(json: any): PageResponseTimeDealSearchResponse {
    return PageResponseTimeDealSearchResponseToJSONTyped(json, false);
}

export function PageResponseTimeDealSearchResponseToJSONTyped(value?: PageResponseTimeDealSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(TimeDealSearchResponseToJSON)),
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'last': value['last'],
    };
}

