/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeDealSearchItem } from './TimeDealSearchItem';
import {
    TimeDealSearchItemFromJSON,
    TimeDealSearchItemFromJSONTyped,
    TimeDealSearchItemToJSON,
    TimeDealSearchItemToJSONTyped,
} from './TimeDealSearchItem';

/**
 * 
 * @export
 * @interface TimeDealSearchResponse
 */
export interface TimeDealSearchResponse {
    /**
     * 
     * @type {number}
     * @memberof TimeDealSearchResponse
     */
    timeDealId?: number;
    /**
     * 
     * @type {string}
     * @memberof TimeDealSearchResponse
     */
    timeDealName?: string;
    /**
     * 
     * @type {Date}
     * @memberof TimeDealSearchResponse
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TimeDealSearchResponse
     */
    endTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof TimeDealSearchResponse
     */
    status?: TimeDealSearchResponseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof TimeDealSearchResponse
     */
    discountRatio?: number;
    /**
     * 
     * @type {Array<TimeDealSearchItem>}
     * @memberof TimeDealSearchResponse
     */
    items?: Array<TimeDealSearchItem>;
}


/**
 * @export
 */
export const TimeDealSearchResponseStatusEnum = {
    Scheduled: 'SCHEDULED',
    Ongoing: 'ONGOING',
    Ended: 'ENDED'
} as const;
export type TimeDealSearchResponseStatusEnum = typeof TimeDealSearchResponseStatusEnum[keyof typeof TimeDealSearchResponseStatusEnum];


/**
 * Check if a given object implements the TimeDealSearchResponse interface.
 */
export function instanceOfTimeDealSearchResponse(value: object): value is TimeDealSearchResponse {
    return true;
}

export function TimeDealSearchResponseFromJSON(json: any): TimeDealSearchResponse {
    return TimeDealSearchResponseFromJSONTyped(json, false);
}

export function TimeDealSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeDealSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'timeDealId': json['timeDealId'] == null ? undefined : json['timeDealId'],
        'timeDealName': json['timeDealName'] == null ? undefined : json['timeDealName'],
        'startTime': json['startTime'] == null ? undefined : (new Date(json['startTime'])),
        'endTime': json['endTime'] == null ? undefined : (new Date(json['endTime'])),
        'status': json['status'] == null ? undefined : json['status'],
        'discountRatio': json['discountRatio'] == null ? undefined : json['discountRatio'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(TimeDealSearchItemFromJSON)),
    };
}

export function TimeDealSearchResponseToJSON(json: any): TimeDealSearchResponse {
    return TimeDealSearchResponseToJSONTyped(json, false);
}

export function TimeDealSearchResponseToJSONTyped(value?: TimeDealSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeDealId': value['timeDealId'],
        'timeDealName': value['timeDealName'],
        'startTime': value['startTime'] == null ? undefined : ((value['startTime']).toISOString()),
        'endTime': value['endTime'] == null ? undefined : ((value['endTime']).toISOString()),
        'status': value['status'],
        'discountRatio': value['discountRatio'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(TimeDealSearchItemToJSON)),
    };
}

