/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeDealSearchItem
 */
export interface TimeDealSearchItem {
    /**
     * 
     * @type {number}
     * @memberof TimeDealSearchItem
     */
    itemId?: number;
    /**
     * 
     * @type {string}
     * @memberof TimeDealSearchItem
     */
    itemName?: string;
    /**
     * 
     * @type {number}
     * @memberof TimeDealSearchItem
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeDealSearchItem
     */
    originalPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeDealSearchItem
     */
    discountedPrice?: number;
}

/**
 * Check if a given object implements the TimeDealSearchItem interface.
 */
export function instanceOfTimeDealSearchItem(value: object): value is TimeDealSearchItem {
    return true;
}

export function TimeDealSearchItemFromJSON(json: any): TimeDealSearchItem {
    return TimeDealSearchItemFromJSONTyped(json, false);
}

export function TimeDealSearchItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeDealSearchItem {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'itemName': json['itemName'] == null ? undefined : json['itemName'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'originalPrice': json['originalPrice'] == null ? undefined : json['originalPrice'],
        'discountedPrice': json['discountedPrice'] == null ? undefined : json['discountedPrice'],
    };
}

export function TimeDealSearchItemToJSON(json: any): TimeDealSearchItem {
    return TimeDealSearchItemToJSONTyped(json, false);
}

export function TimeDealSearchItemToJSONTyped(value?: TimeDealSearchItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'itemName': value['itemName'],
        'quantity': value['quantity'],
        'originalPrice': value['originalPrice'],
        'discountedPrice': value['discountedPrice'],
    };
}

