/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeDealCreateItemDetail
 */
export interface TimeDealCreateItemDetail {
    /**
     * 
     * @type {number}
     * @memberof TimeDealCreateItemDetail
     */
    itemId?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeDealCreateItemDetail
     */
    quantity?: number;
}

/**
 * Check if a given object implements the TimeDealCreateItemDetail interface.
 */
export function instanceOfTimeDealCreateItemDetail(value: object): value is TimeDealCreateItemDetail {
    return true;
}

export function TimeDealCreateItemDetailFromJSON(json: any): TimeDealCreateItemDetail {
    return TimeDealCreateItemDetailFromJSONTyped(json, false);
}

export function TimeDealCreateItemDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeDealCreateItemDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function TimeDealCreateItemDetailToJSON(json: any): TimeDealCreateItemDetail {
    return TimeDealCreateItemDetailToJSONTyped(json, false);
}

export function TimeDealCreateItemDetailToJSONTyped(value?: TimeDealCreateItemDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'quantity': value['quantity'],
    };
}

