/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeDealCreateItem } from './TimeDealCreateItem';
import {
    TimeDealCreateItemFromJSON,
    TimeDealCreateItemFromJSONTyped,
    TimeDealCreateItemToJSON,
    TimeDealCreateItemToJSONTyped,
} from './TimeDealCreateItem';

/**
 * 
 * @export
 * @interface TimeDealCreateResponse
 */
export interface TimeDealCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof TimeDealCreateResponse
     */
    timeDealId?: number;
    /**
     * 
     * @type {string}
     * @memberof TimeDealCreateResponse
     */
    timeDealName?: string;
    /**
     * 
     * @type {string}
     * @memberof TimeDealCreateResponse
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof TimeDealCreateResponse
     */
    endTime?: string;
    /**
     * 
     * @type {number}
     * @memberof TimeDealCreateResponse
     */
    discountRatio?: number;
    /**
     * 
     * @type {Array<TimeDealCreateItem>}
     * @memberof TimeDealCreateResponse
     */
    items?: Array<TimeDealCreateItem>;
}

/**
 * Check if a given object implements the TimeDealCreateResponse interface.
 */
export function instanceOfTimeDealCreateResponse(value: object): value is TimeDealCreateResponse {
    return true;
}

export function TimeDealCreateResponseFromJSON(json: any): TimeDealCreateResponse {
    return TimeDealCreateResponseFromJSONTyped(json, false);
}

export function TimeDealCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeDealCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'timeDealId': json['timeDealId'] == null ? undefined : json['timeDealId'],
        'timeDealName': json['timeDealName'] == null ? undefined : json['timeDealName'],
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'discountRatio': json['discountRatio'] == null ? undefined : json['discountRatio'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(TimeDealCreateItemFromJSON)),
    };
}

export function TimeDealCreateResponseToJSON(json: any): TimeDealCreateResponse {
    return TimeDealCreateResponseToJSONTyped(json, false);
}

export function TimeDealCreateResponseToJSONTyped(value?: TimeDealCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeDealId': value['timeDealId'],
        'timeDealName': value['timeDealName'],
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'discountRatio': value['discountRatio'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(TimeDealCreateItemToJSON)),
    };
}

