/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeDealModalCreateResponse
 */
export interface TimeDealModalCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof TimeDealModalCreateResponse
     */
    itemId?: number;
    /**
     * 
     * @type {string}
     * @memberof TimeDealModalCreateResponse
     */
    itemName?: string;
    /**
     * 
     * @type {number}
     * @memberof TimeDealModalCreateResponse
     */
    originalPrice?: number;
}

/**
 * Check if a given object implements the TimeDealModalCreateResponse interface.
 */
export function instanceOfTimeDealModalCreateResponse(value: object): value is TimeDealModalCreateResponse {
    return true;
}

export function TimeDealModalCreateResponseFromJSON(json: any): TimeDealModalCreateResponse {
    return TimeDealModalCreateResponseFromJSONTyped(json, false);
}

export function TimeDealModalCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeDealModalCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'itemName': json['itemName'] == null ? undefined : json['itemName'],
        'originalPrice': json['originalPrice'] == null ? undefined : json['originalPrice'],
    };
}

export function TimeDealModalCreateResponseToJSON(json: any): TimeDealModalCreateResponse {
    return TimeDealModalCreateResponseToJSONTyped(json, false);
}

export function TimeDealModalCreateResponseToJSONTyped(value?: TimeDealModalCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'itemName': value['itemName'],
        'originalPrice': value['originalPrice'],
    };
}

