/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeDealCreateItemDetail } from './TimeDealCreateItemDetail';
import {
    TimeDealCreateItemDetailFromJSON,
    TimeDealCreateItemDetailFromJSONTyped,
    TimeDealCreateItemDetailToJSON,
    TimeDealCreateItemDetailToJSONTyped,
} from './TimeDealCreateItemDetail';

/**
 * 
 * @export
 * @interface TimeDealCreateRequest
 */
export interface TimeDealCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof TimeDealCreateRequest
     */
    title?: string;
    /**
     * 
     * @type {Date}
     * @memberof TimeDealCreateRequest
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TimeDealCreateRequest
     */
    endTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof TimeDealCreateRequest
     */
    discountRatio?: number;
    /**
     * 
     * @type {Array<TimeDealCreateItemDetail>}
     * @memberof TimeDealCreateRequest
     */
    items?: Array<TimeDealCreateItemDetail>;
}

/**
 * Check if a given object implements the TimeDealCreateRequest interface.
 */
export function instanceOfTimeDealCreateRequest(value: object): value is TimeDealCreateRequest {
    return true;
}

export function TimeDealCreateRequestFromJSON(json: any): TimeDealCreateRequest {
    return TimeDealCreateRequestFromJSONTyped(json, false);
}

export function TimeDealCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeDealCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'startTime': json['startTime'] == null ? undefined : (new Date(json['startTime'])),
        'endTime': json['endTime'] == null ? undefined : (new Date(json['endTime'])),
        'discountRatio': json['discountRatio'] == null ? undefined : json['discountRatio'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(TimeDealCreateItemDetailFromJSON)),
    };
}

export function TimeDealCreateRequestToJSON(json: any): TimeDealCreateRequest {
    return TimeDealCreateRequestToJSONTyped(json, false);
}

export function TimeDealCreateRequestToJSONTyped(value?: TimeDealCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'startTime': value['startTime'] == null ? undefined : ((value['startTime']).toISOString()),
        'endTime': value['endTime'] == null ? undefined : ((value['endTime']).toISOString()),
        'discountRatio': value['discountRatio'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(TimeDealCreateItemDetailToJSON)),
    };
}

