/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateImageRequest
 */
export interface UpdateImageRequest {
    /**
     * 
     * @type {Blob}
     * @memberof UpdateImageRequest
     */
    image: Blob;
}

/**
 * Check if a given object implements the UpdateImageRequest interface.
 */
export function instanceOfUpdateImageRequest(value: object): value is UpdateImageRequest {
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function UpdateImageRequestFromJSON(json: any): UpdateImageRequest {
    return UpdateImageRequestFromJSONTyped(json, false);
}

export function UpdateImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateImageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'],
    };
}

export function UpdateImageRequestToJSON(json: any): UpdateImageRequest {
    return UpdateImageRequestToJSONTyped(json, false);
}

export function UpdateImageRequestToJSONTyped(value?: UpdateImageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
    };
}

